### ISSUE TITLE
Use HASS logging levels

### ISSUE THREAD

**Issue by adamcstephens** [sandlewoodshire/LennoxiComfort#1]
Right now there's a print statement that is outputting from the api calls. That seems useful, but probably only if debug logging is enabled for the component.

https://github.com/sandlewoodshire/LennoxiComfort/blob/4c5c3a84a539fb09e913f7eb675b161925b52f16/api/lennox_api.py#L201

**Comment by sandlewoodshire** [comment]
I had that on for debugging an issue I ran into the other day.  Guess I forgot to comment it back out before I committed the most recent changes.  I guess I do need a programmatic way for enabling debug messages instead of manually adding and removing '#' from lines.  I will comment it out for now and work on a debug solution as well.

**Comment by adamcstephens** [comment]
If you use the built in logger, you can customize the level on a per-component basis:

https://www.home-assistant.io/components/logger/

**Comment by sandlewoodshire** [comment]
Great idea. Python logging is now implemented. API will log messages as specified by the configured logging level.  Thanks for helping me make this better.  

On a side note, I started a blog and to provide some name coordination I am changing my github account name to 'thevoltagesource'.

**Comment by adamcstephens** [comment]
Thanks!
